-- schema.sql
DROP TABLE IF EXISTS ROLE;
--CREATE TABLE IF NOT EXISTS ROLE (
CREATE TABLE ROLE (
  Id          BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Name    VARCHAR(500) NOT NULL
);  

DROP TABLE IF EXISTS Users;
CREATE TABLE Users (
  Id          BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Username    VARCHAR(50) NOT NULL,
  Password    VARCHAR(50)
  );

DROP TABLE IF EXISTS Category;
--CREATE TABLE IF NOT EXISTS Category (
CREATE TABLE Category (
  CategoryId    BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Category      VARCHAR(500)
);  

DROP TABLE IF EXISTS Expense;
--CREATE TABLE IF NOT EXISTS Expense (
CREATE TABLE Expense (
  ExpenseId      BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  ExpenseName    VARCHAR(500),
  Amount         DOUBLE,
  CreatedDate  DateTime,
  Comments     VARCHAR(500),
  CategoryId   BIGINT
);  

DROP TABLE IF EXISTS Member;
--CREATE TABLE IF NOT EXISTS Member (
CREATE TABLE Member (
  MemberId    BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  FullName    VARCHAR(500),
  PhoneNumber VARCHAR(50),
  EmailId     VARCHAR(90)
);  

DROP TABLE IF EXISTS Expense;
--CREATE TABLE IF NOT EXISTS Expense (
CREATE TABLE Expense (
  ExpenseId      BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  ExpenseName    VARCHAR(500),
  Amount         DOUBLE,
  CreatedDate    DateTime,
  Comments       VARCHAR(500),
  MemberId       BIGINT,
  CategoryId     BIGINT
);  

DROP TABLE IF EXISTS FILE_UPLOAD;
--CREATE TABLE IF NOT EXISTS FILE_UPLOAD (
CREATE TABLE FILE_UPLOAD (
  ExpenseId   BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Image       LONGBLOB
);  
